### ISSUE TITLE
how to build jar?

### ISSUE THREAD

**Issue by goodale** [mmalmeida/displaytag#1]
I am eager to use your 1.3-SNAPSHOT to work around the java.lang.NoSuchMethodError: com.lowagie.text.Table.setDefaultVerticalAlignment
issue you've fixed.  

However, I don't see precompiled jar files or a build file.   How does one go about building the project into the two jar files? (display-tag-1.3-SNAPSHOT.jar and display-export-poi-1.3-SNAPSHOT.jar)?

Thank you in advance for your help,
Steve

**Comment by mmalmeida** [comment]
Hi Steve,

I hope this can help you!

This are Maven projects. In order to compile them you should:
1. Download the source
2. Run the maven package goal (literally, "mvn  package" in the parent directory). 

The jars will be created in the build directories of each of the sub-projects.

**Comment by goodale** [comment]
Thank you!  that is a big help.  (I'm familiar with Ant but not Maven yet)
