### ISSUE TITLE
enhancing displaytag to support jQuery themes and client-side sorting

### ISSUE THREAD

**Issue by goodale** [mmalmeida/displaytag#2]
I'm interested in hiring a developer to enhance your fork of DisplayTag to support jQuery's themes and support things such as client-side sorting.   Any contributors interested?  

I've looked at javascript-based alternatives but like that DisplayTag includes ability to generate XLS and PDF so easily.  I've looked at JMesa as it seems to be more widely supported but it seems slow, heavy and tries to do too much with the editing. So hoping DisplayTag will stay alive...

Steve

**Comment by mmalmeida** [comment]
Hi @goodale,
I apologise for the late reply.

Are you still interested in displaytag? I do have developers who can help you out.

Let me know your thoughs so we can then discuss details by email.

**Comment by goodale** [comment]
Yes.  Specifically, looking for it to be updated to support the latest POI library (thus .xlsx files) and also integrate with tablesorter jquery library.    Please contact me at:  steve at regattacentral dot com
